name: Release
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
